# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0

archives:
- replacements:
    darwin: Darwin
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  skip: true
brew:
  name: diceroller
  github:
    owner: lukemilby
    name: homebrew-diceroller
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
  skip_upload: trueldawldalw
  install: bin.install "diceroller"
  description: Deliver Go binaries as fast and easily as possible
  homepage: https://derp.com
