# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
brew:
  name: diceroller
  github:
    owner: lukemilby
    name: homebrew-diceroller
  skip_upload: auto
  homepage:  https://derp.com
  description: Deliver Go binaries as fast and easily as possible
archives:
- replacements:
    darwin: Darwin
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-alpha"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
