# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-alpha"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
# .goreleaser.yml
brew:
  # Name template of the recipe
  # Default to project name
  name: diceroller

  # Repository to push the tap to.
  github:
    owner: lukemilby
    name: homebrew-diceroller

  # Template for the url.
  # Default is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  url_template: "http://github.com/lukemilby/diceroller/releases/{{ .Tag }}/{{ .ArtifactName }}"
  folder: Formula
  skip_upload: false
release:
  github:
    owner: lukemilby
    name: homebrew-diceroller
